-- Originally written by Antonio Terceiro
-- https://github.com/terceiro/awesome-freedesktop
-- Hacked by Alex Y. <yakushev.alex@gmail.com>

-- Grab environment
local utils = require("menubar.utils")
local io = io
local ipairs = ipairs
local awful = awful
local string = string

module("menubar.menu_gen")

all_menu_dirs = { '/usr/share/applications/' }
output_filename = awful.util.getdir("cache") .. "/cached_menu_data"
eof = "-- END OF FILE"

all_categories = {
   { app_type = "AudioVideo", name = "Multimedia",
     icon = utils.lookup_icon("applications-multimedia.png"), use = true },
   { app_type = "Development", name = "Development",
     icon = utils.lookup_icon("applications-development.png"), use = true },
   { app_type = "Education", name = "Education",
     icon = utils.lookup_icon("applications-science.png"), use = false },
   { app_type = "Game", name = "Games",
     icon = utils.lookup_icon("applications-games.png"), use = true },
   { app_type = "Graphics", name = "Graphics",
     icon = utils.lookup_icon("applications-graphics.png"), use = true },
   { app_type = "Office", name = "Office",
     icon = utils.lookup_icon("applications-office.png"), use = true },
   { app_type = "Network", name = "Internet",
     icon = utils.lookup_icon("applications-internet.png"), use = true },
   { app_type = "Settings", name = "Settings",
     icon = utils.lookup_icon("applications-utilities.png"), use = false },
   { app_type = "System", name = "System Tools",
     icon = utils.lookup_icon("applications-system.png"), use = true },
   { app_type = "Utility", name = "Accessories",
     icon = utils.lookup_icon("applications-accessories.png"), use = true }
}

local function get_category_and_number_by_type(app_type)
   for i, v in ipairs(all_categories) do
      if app_type == v.app_type then
         return i, v
      end
   end
   return nil
end

local function esc_q(s)
   if s then
      -- Escape slashes and remove all non-printable characters
      return string.gsub(string.gsub(s, "'" ,"\\'"),
                         "(.)", function(c)
                                   if string.byte(c, 1) > 31 then
                                      return c
                                   else
                                      return ""
                                   end
                                end)
   else
      return ""
   end
end

function generate()
   f = io.open(output_filename, 'w')
   f:write('-- AUTOGENERATED. BETTER NOT MODIFY.\n')

   for i, dir in ipairs(all_menu_dirs) do
      local entries = utils.parse_dir(dir) do
         for i, program in ipairs(entries) do
            -- check whether to include in the menu
            if program.show and program.Name and program.cmdline then
               local target_category = nil
               if program.categories then
                  for _, category in ipairs(program.categories) do
                     local category_id, cat = get_category_and_number_by_type(category)
                     if category_id and cat.use then
                        target_category = category_id
                        break
                     end
                  end
               end
               if target_category then
                  f:write(
                     string.format("%s\n%s\n%s\n%s\n",
                                   esc_q(program.Name), esc_q(program.cmdline),
                                   utils.lookup_icon(esc_q(program.icon_path)),
                                   target_category))
               end
            end
         end
      end
   end
   f:write(eof)
   f:close()
end
